name: to_do_list_new
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">= 3.0.0 <4.0.0"


dependencies:
  connectivity_plus: ^4.0.1
  dio: ^5.2.1+1
  envied: ^0.3.0+3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  get_it: ^7.6.0
  intl: ^0.18.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  mobx: ^2.2.0
  mobx_codegen: ^2.3.0
  path_provider: ^2.0.15
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  isar_generator: ^3.1.0+1
  envied_generator: ^0.3.0+3


flutter:
  uses-material-design: true

  
  assets:
    - l10n/
    - assets/
    - assets/icons/


