name: to_do_list_new
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  path_provider: ^2.0.15
  cupertino_icons: ^1.0.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  mobx_codegen:  

 
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  
  assets:
    - assets/
    - assets/icons/


