// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2ECfVa0TgdLVoZImIZOnNMQDN7l_VzE0',
    appId: '1:996005045115:web:ad9a23ce471baed3f693de',
    messagingSenderId: '996005045115',
    projectId: 'taskbookyan',
    authDomain: 'taskbookyan.firebaseapp.com',
    storageBucket: 'taskbookyan.appspot.com',
    measurementId: 'G-3Y86R5E17D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGT8yJ7oZgrrv8Nl8Vl9B_mcpThYG-aIE',
    appId: '1:996005045115:android:4c3d9d9c549600fdf693de',
    messagingSenderId: '996005045115',
    projectId: 'taskbookyan',
    storageBucket: 'taskbookyan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFln5tyyPp6htWO46L0mMTc32qyLgqHI4',
    appId: '1:996005045115:ios:1bb09aa4109eeec1f693de',
    messagingSenderId: '996005045115',
    projectId: 'taskbookyan',
    storageBucket: 'taskbookyan.appspot.com',
    iosClientId: '996005045115-cbommdekmd355jeemacml06e5eh6jsba.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoListNew',
  );
}
