name: main

on: [push, workflow_dispatch]

jobs:
  analyze:
    name: Run analyzer and formatter
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          cache: true
      - run: flutter pub get
      - run: flutter analyze
      - run: dart format --set-exit-if-changed lib/
  build:
    needs: [ analyze ]
    name: Build android on Mac OS
    runs-on: macos-11
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Set up JDK 11
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.10.5
        with:
          java-version: 11
          distribution: temurin
      - name: Build apk for android
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          flutter build apk --dart-define=TOKEN=$TOKEN
